spring.application.name=roadside-assistance
spring.datasource.url=jdbc:mysql://localhost:3306/roadside_assistance
spring.datasource.username=root
spring.datasource.password={PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
